/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:9d0caeae-b0da-4528-a066-b40fabd0d7d3",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_pAivLhXjZ",
    "aws_user_pools_web_client_id": "24s5aju5tfmdfjfr3e3upj1aj9",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://ukeyvcxejvczhdsjbc4wo2p52m.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-fpcc5vohofcidfipwhdlcgdmwe",
    "aws_user_files_s3_bucket": "demo-bucket222520-dev",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
